# -*- coding: utf-8 -*-
"""layer1_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CenlRXW9XKc6h-uVLuYraavwH-Qkc7Cc
"""

# Now run Layer 1 pipeline
import requests
from supabase import create_client
from datetime import datetime
import os

# Your credentials (paste them directly for now)
SUPABASE_URL = 'https://xdsfbpvqtqeyvuddxheo.supabase.co'
SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkc2ZicHZxdHFleXZ1ZGR4aGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2NTEzNDQsImV4cCI6MjA5NjIyNzM0NH0.8gk4UZ1ioTiEprZW17levkO_udtd7Ay_sof49tW6Io0'

print("="*50)
print(f"AquaAdapt Pro - Layer 1 Pipeline")
print(f"Run at: {datetime.now()}")
print("="*50)

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# Fetch weather data
lat, lon = 18.408, 76.565
url = "https://api.open-meteo.com/v1/forecast"
params = {
    "latitude": lat,
    "longitude": lon,
    "hourly": "temperature_2m,precipitation",
    "timezone": "Asia/Kolkata",
    "forecast_days": 7
}

response = requests.get(url, params=params)
data = response.json()

# Process data
temps = data['hourly']['temperature_2m']
rains = data['hourly']['precipitation']
times = data['hourly']['time']

records = []
for i in range(0, len(temps), 24):
    if i + 24 <= len(temps):
        records.append({
            "location_name": "Latur",
            "date": times[i][:10],
            "temp_max_c": max(temps[i:i+24]),
            "rain_mm": sum(rains[i:i+24]),
            "fetched_at": datetime.now().isoformat()
        })

# Store in Supabase
result = supabase.table("weather_data").insert(records).execute()
print(f"✅ Stored {len(records)} records at {datetime.now()}")

# Verify
verify = supabase.table("weather_data").select("*").execute()
print(f"📁 Total rows in database: {len(verify.data)}")